### ISSUE TITLE
Error:    0: No matching key found

### ISSUE THREAD

**Issue by nguyenbaongocbkhn** [systemd-run/manuals#12]
I setup ok to this: please fix again code

root@ngocnb:~# namada client transfer \
  --source faucet \
  --target $WALLET \
  --token NAM \
  --amount 1000 \
>  --signing-keys $WALLET
Error:
   0: No matching key found

Location:
   /root/namada/apps/src/lib/cli/client.rs:68

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
root@ngocnb:~#

**Comment by encipher88** [comment]
chain halted and faucet is not available from cli
